### PR TITLE
Enhancement #1316 - Add settings from comment notify module

### PR DESCRIPTION
**Pull request by gielfeldt**

### CODE REVIEW

**Comment by cableman** [comment]
Please use the standard Drupal format for commit messages and also link back to the issue.

The format is "Issue #XXX by YYY: Enabled comments for ding events".

For more information please see: https://www.drupal.org/node/52287

**Comment by cableman** [comment]
The message (Du kan slå denne funktion fra ved at logge ind og ændre indstillingerne på din brugerprofil på [comment:node:author:edit-url].) is that possible for provider users as they don't have the normal user account edit fields ?

**Comment by guddo** [comment]
https://github.com/ding2/ding2/pull/105

You can close this PR.

**Comment by kasperg** [comment]
Thanks @guddo .

**Pull request closed without merging**
